name: github action for three tier crud application
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up Helm
      uses: azure/setup-helm@v3
      with:
        version: 'v3.14.0'
    - name: Set up Kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'v1.32.0'
    - name: Install dependencies (kubectl, helm, minikube)
      run: |
        # Install kubectl
        curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
        sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
        # Install helm
        curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
        # Install minikube
        curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
        sudo install minikube-linux-amd64 /usr/local/bin/minikube
    - name: Start minikube
      run: |
        minikube start
    - name: Run minikube tunnel in background
      run: |
        nohup sudo minikube tunnel > tunnel.log 2>&1 &
        sleep 10 # wait a bit for tunnel to establish
    - name: Check minikube status
      run: |
        minikube status
        kubectl get nodes -o wide
    - name: Adding bitnami repo and running postgres database from bitnami
      run: |
        helm repo add bitnami https://charts.bitnami.com/bitnami
        helm repo update
        helm install my-postgres bitnami/postgresql  --set auth.username=cruduser  --set auth.password=password  --set auth.database=cruddb
        sleep 15
        #checking whether ethe pod is running or not
        kubectl get pods
    - name: installing backend
      run: |
        helm install backendapp backendchart
    - name: installing frontend
      run: |
        helm install frontend frontendapp
    - name: wait for 50 sec for running state of pods
      run: |
        sleep 50
        kubectl get pods
        kubectl get svc
